# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0002_auto_20170523_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='votes',
        ),
    ]
